version: "3.7"
services:
  textile_threads:
    container_name: "textile_threads"
    build: 
      context: ../go-textile-threads/.
    command: "daemon --repo=/data/threads --hostAddr=/ip4/127.0.0.1/tcp/4006 --hostProxyAddr=/ip4/127.0.0.1/tcp/5050 --apiAddr=/ip4/127.0.0.1/tcp/9090 --apiProxyAddr=/ip4/127.0.0.1/tcp/9091"
    ports:
      - "4006:4006"
      - "5050:5050"
      - "9090:9090"
      - "9091:9091"
  textile_daemon:
    container_name: "textile_daemon"
    build: .
    environment:
      DOCKER_COMPOSE: "true"
    depends_on:
      - textile_threads
    links: 
      - textile_threads
    ports:
      - "3006:3006"